# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: r

# sudo: required # for new repository

install:
  - ./travis-tool.sh github_package jimhester /covr

after_success:
  - Rscript -e 'library(covr);coveralls()'
